services:
  # Backend service
  - type: web
    name: moviereco-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        value: https://moviereco-frontend.onrender.com
      - key: ALLOW_CREDENTIALS
        value: "false"

  # Frontend service
  - type: static
    name: moviereco-frontend
    buildCommand: mkdir -p dist && cp -r frontend/* dist/
    staticPublishPath: ./dist
    envVars:
      - key: API_URL
        value: https://mrs-backend.onrender.com